### ISSUE TITLE
Add grafana-dashboard?

### ISSUE THREAD

**Issue by batazor** [CrunchyData/pgmonitor-extension#6]
It would be cool to add a grafana-dashboard so that you could immediately see a visualization on new data

**Comment by keithf4** [comment]
Please see the pgMonitor project if you're looking for an application of this extension with Prometheus/Grafana

https://github.com/CrunchyData/pgmonitor

**Comment by keithf4** [comment]
I've added a reference to the pgMonitor project in the top level readme. Thanks for your interest in the project!
